name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: echo '${{ secrets.DOCKER_PWD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Docker Build
      run: docker build -t 19921229/GenuineMe-server .
    - name: Docker Push
      run: docker push 19921229/GenuineMe-server
