name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run:  docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PWD}}
    - name: Docker Build
      run: docker build -t 19921229/genuineme-server .
    - name: Docker Push
      run: docker push 19921229/genuineme-server
